P1_MVCStoreWebApplication/NotAmoebaStoreApplicationMVC/NotAmoebaStoreApplicationMVC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelLayer.ViewModels;

namespace NotAmoebaStoreApplicationMVC.Controllers
{
    public class CustomerController : Controller
    {
        private BusinessLogicClass _businessLogicClass;
        // GET: CustomerController

        public CustomerController(BusinessLogicClass businessLogicClass)
        {
            _businessLogicClass = businessLogicClass;
        }
        
        //public ActionResult Index()
        //{
        //    return View();
        //}

        [ActionName("CustomerList")]
        public ActionResult Index()
        {
            List<CustomerViewModel> customerViewModelList = _businessLogicClass.CustomerList();
            return View(customerViewModelList);
        }

        // GET: CustomerController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CustomerController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomerController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomerController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CustomerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

P1_MVCStoreWebApplication/NotAmoebaStoreApplicationMVC/NotAmoebaStoreApplicationMVC/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelLayer.ViewModels;

namespace NotAmoebaStoreApplicationMVC.Controllers
{
    public class ShopController : Controller
    {
        private BusinessLogicClass _businessLogicClass;
        public ShopController(BusinessLogicClass businessLogicClass)
        {
            _businessLogicClass = businessLogicClass;
        }
        // GET: InventoryController

        [ActionName("ShowStores")]
        public ActionResult ShowStores()
        {
            List<ShopViewModel> storeViewModelList = _businessLogicClass.StoreList();
            return View(storeViewModelList);
        }

        [ActionName("ShowInventory")]
        public ActionResult Index()
        {
            List<InventoryViewModel> inventoryViewModelList = _businessLogicClass.InventoryList();
            return View(inventoryViewModelList);
        }

        [ActionName("Quantity")]
        public ActionResult Quantity()
        {
            return View("Quantity");
        }

        [ActionName("DeduceQuantity")]
        public ActionResult DeduceQuantity(int quantity)
        {
            return View("DeduceQuantity" ,quantity);

        }

        // GET: InventoryController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: InventoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InventoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InventoryController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: InventoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InventoryController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: InventoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

P1_MVCStoreWebApplication/NotAmoebaStoreApplicationMVC/NotAmoebaStoreApplicationMVC/Views/Shared/DisplayCustomerDetails.cshtml
@model ModelLayer.ViewModels.CustomerViewModel

@{
    ViewData["Title"] = "DisplayCustomerDetails";
}

<h1>DisplayCustomerDetails</h1>

<div>
    <h4>LoginCustomerViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a> | 
    <a asp-controller="Customer" asp-action="CustomerList">View A List Of All Customers</a> | 
    <a asp-controller="Shop" asp-action="ShowStores">Let's Start Shopping!</a>
</div>

P1_MVCStoreWebApplication/NotAmoebaStoreApplicationMVC/NotAmoebaStoreApplicationMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - !NotAmoeba!</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">!NotAmoeba!</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NotAmoebaStoreApplicationMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>